Now?

diff --git a/0-git_pusher b/0-git_pusher
--- a/0-git_pusher
+++ b/0-git_pusher
@@ -3,9 +3,9 @@ git add .
 echo "Commit Message:"
 read commit_message
 git commit -m "$commit_message"
-result=#?
+result=$?
 if [$result -e20]; then
-git push
+	git push
 else
-echo "Commit Failed"
+	echo "Commit Failed"
 fi
